version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
#    volumes:
#      - "./volumes/postgres"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ruyoutor@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge